<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forgot password_txtrywd2t8jg</name>
   <tag></tag>
   <elementGuidId>580aebe7-bd1d-413a-bf58-4b6677c4457e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtrywd2t8jg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtrywd2t8jg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6400d4d-59a6-49be-86dd-62c8f469292a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8c64ab42-ba81-46ce-b3dc-32ed2e0324c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your Password</value>
      <webElementGuid>c2c66fc7-be14-4fbd-b3c0-9aa2d7e320e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtrywd2t8jg</value>
      <webElementGuid>c225afd8-eefe-4ea4-96fc-0bf791a398c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-appended</value>
      <webElementGuid>7ab32314-96e0-49ee-bae0-79dc9d2fabef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtrywd2t8jg&quot;)</value>
      <webElementGuid>b5e3e416-3665-41cf-99db-fcbc350b47fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtrywd2t8jg']</value>
      <webElementGuid>a145676e-c7e5-46b3-9148-46d2e8eaaf50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/span/form/span[2]/div/div[2]/input</value>
      <webElementGuid>890b21d3-2e1d-4867-b617-dab6af4d5b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ad543dfd-76d2-4291-84f3-a7d34ec2255b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Enter your Password' and @id = 'txtrywd2t8jg']</value>
      <webElementGuid>df237765-6211-4c55-9943-0736ede6fedb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
