<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forgot password_txtrgeyuetlr</name>
   <tag></tag>
   <elementGuidId>820ab287-b466-4bce-96f1-72e74ceea33b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtrgeyuetlr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtrgeyuetlr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7757efb-7e5d-4737-a85e-7cad1d6f0e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c7e8ebc2-3729-4c27-83a6-13613138c129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your Password</value>
      <webElementGuid>40f5c80d-4022-4c03-988a-999e06fac1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtrgeyuetlr</value>
      <webElementGuid>e5974a16-18a7-42df-94c7-4c30c883766d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-appended</value>
      <webElementGuid>34d0f932-e72f-4845-96e5-792b264418e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtrgeyuetlr&quot;)</value>
      <webElementGuid>2942052a-c1e5-4554-8042-21a211afc0ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtrgeyuetlr']</value>
      <webElementGuid>30747882-8a54-4848-8c60-45bb4e967364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/span/form/span[2]/div/div[2]/input</value>
      <webElementGuid>ccb98745-bc93-4146-bf4c-41fd30b739a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>f5abcedf-0c64-4986-b306-e044d6ff5e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Enter your Password' and @id = 'txtrgeyuetlr']</value>
      <webElementGuid>33d1cae5-0739-426d-a8b6-10f000a87332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
