<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtUser</name>
   <tag></tag>
   <elementGuidId>b28d8890-213c-4043-83d8-d35c44c8e5da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c85c779d-bf83-49f5-b921-63e8880a092e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your Email Address</value>
      <webElementGuid>d821f461-7125-49b0-b93e-d373de0fc9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>8fc792e6-c18a-443b-9166-aa78974d8f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6fe37e4d-c611-4c05-a293-3d785443fb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUser</value>
      <webElementGuid>5bd88cfd-05f7-4096-bf70-334f2d579c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUser&quot;)</value>
      <webElementGuid>e26c6d14-fb7f-4e7e-a6e4-a58504640926</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtUser']</value>
      <webElementGuid>7378682d-a081-4fbe-ba66-d17c3b32fb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/span/form/span/div/input</value>
      <webElementGuid>b5a5420f-51f5-445e-98b4-bd979bc71ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a6b385d0-353e-4cc2-b6a3-e73462e43ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your Email Address' and @type = 'email' and @id = 'txtUser']</value>
      <webElementGuid>99a56f0f-8711-4237-af02-6b55b5e29e21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
